// vendor_schema_proposal.ts
//
// PROPOSAL ONLY -- not wired into the app. Generated by inspecting the raw
// AppSheet recovery data in frontend/lib/appsheet-tables.json, specifically
// the "vendors" and "vendor-resources" tables' <thead> columns, cross-checked
// against frontend/lib/appsheet-tables.ts's existing TABLE_CONFIGS entries
// for those two tables (which already parse these exact columns for other
// purposes -- see VENDORS_PREFIX and the "vendor-resources" config there).
//
// Source: "vendors" table -- 37 records, 7 columns (prefix "nerd-col-vend-"):
//   Row #, Vendor Name, Vendor Website, Last Updated, Added to Site, Notes,
//   NCADEMI Vendor URL
//
// Source: "vendor-resources" table -- 31 records, 9 columns
// (prefix "nerd-col-vres-"):
//   Row #, Row ID, Resource Name, Vendor, URL, Source, Label, Date,
//   Added to Site
//
// Row # is a source-capture artifact (position in the AppSheet export), not
// stable data -- dropped from both interfaces below. Row ID (vendor-resources
// only) IS a stable AppSheet identifier and is kept as `id`.
//
// "Source" on vendor-resources is "Internal" or "External" in the sampled
// data -- the same two values frontend/lib/appsheet-tables.ts already uses to
// split a product's own vendor_resources ("Internal") from other_resources
// ("External"); see getVendorResourcesForProduct() there. Modeled as a union,
// not a bare string.
//
// "Added to Site" is "Yes"/"No" in both tables -- modeled as boolean.
//
// is the vendor's own external site; "NCADEMI Vendor URL" is that vendor's
// page ON ncademi.org. Named accordingly below (vendor_website_url vs.
// vendor_directory_url) rather than both being called "url".
//
// VendorResources are linked back to their vendor by exact Vendor Name
// match, not a foreign-key id -- because that's how the existing appsheet
// code does the same join today (see getVendorResourcesForProduct() /
// the "vendors" table lookup in appsheet-tables.ts). A real scraper/migrator
// would resolve this join once and nest the result, as modeled here via
// VendorRecord.resources -- this file does not implement that join, only the
// shape it would produce.

/** One row from the "vendor-resources" table, joined onto its vendor. */
export interface VendorResource {
  /** Row ID -- the one genuinely stable identifier AppSheet assigned this row. */
  id: string;
  /** Resource Name */
  text: string;
  /** URL */
  url: string;
  /**
   * Source -- "Internal" (the vendor's own resource) or "External"
   * (a third-party resource about the vendor). Only these two values were
   * observed in the sampled data.
   */
  source: "Internal" | "External";
  /** Label -- e.g. "Statement/Policy". Frequently blank in the source data. */
  label: string | null;
  /** Date -- free-text timestamp as AppSheet exported it (e.g. "2/17/2026 9:35:34 AM"), not parsed/normalized here. */
  date: string | null;
  /** Added to Site -- "Yes"/"No" in the source, modeled as boolean. */
  added_to_site: boolean;
}

/** Represents a product linked to this vendor from the NCADEMI live directory. */
export interface VendorProductLink {
  product_name: string;
  ncademi_product_url: string;
}

/** One row from the "vendors" table, with its vendor-resources rows joined in by Vendor Name. */
export interface VendorRecord {
  /** Vendor Name -- the join key used to match vendor-resources rows above. */
  vendor_name: string;
  /** Vendor Website -- the vendor's own external site (nullable: several sampled rows had no linked URL). */
  vendor_website_url: string | null;
  /** NCADEMI Vendor URL -- this vendor's own page on ncademi.org, distinct from vendor_website_url above. */
  vendor_directory_url: string | null;
  /** Last Updated -- free-text timestamp as AppSheet exported it (e.g. "2/17/26, 10:27 AM"), not parsed/normalized here. */
  last_updated: string | null;
  /** Added to Site -- "Yes"/"No" in the source, modeled as boolean. */
  added_to_site: boolean;
  /** Notes -- free text, frequently blank in the source data. */
  notes: string | null;
  /** Not a source column -- vendor-resources rows joined in by exact Vendor Name match (see the file header). */
  resources: VendorResource[];
  /** Products associated with this vendor, extracted from the vendor directory page. */
  products: VendorProductLink[];
}

/**
 * Top-level file shape, mirroring the $schema_version/$meta/products
 * envelope already used by frontend/lib/published-tables.json (see
 * PublishedProductRecord's file in published-tables.ts) rather than
 * inventing a new envelope convention for this one file.
 */
export interface VendorsFile {
  $schema_version: number;
  $meta: {
    purpose: string;
    source_listing_url: string;
    snapshot_taken_at: string;
    total_vendors: number;
    generated_from: string;
  };
  vendors: VendorRecord[];
}
